<?php 
	require_once "functions.php";

		$userId = $_SESSION['active']['user_id'];
		$basket_state = $link->escape_string($_POST['basket_state']); //generated by AJAX call
		$item_id = $link->escape_string($_POST['inbasket']);
		if($_POST['ajax'] == 'true') {
			$ajax = true;
		}

		if ($ajax == true) {
			if(is_numeric($item_id) && ($basket_state == 0 || $basket_state == 1)) {
				$query = "UPDATE `items` SET `item_inbasket` = '$basket_state' WHERE `item_id` = '$item_id' AND `user_id` = '$userId'";
				$link->query($query);
			} else {
				die('An error has occured. Please contact the site administrator');
			}	
		}
		

?>